### ISSUE TITLE
Punctuation after tick

### ISSUE THREAD

**Issue by don-reba** [uptech/vim-slack-format#1]
The syntax fails to stop highlighting when a closing tick is followed by punctuation.

Expected: Your program starts with **\`main()\`**. This function is called by the C++ runtime.
Actual: Your program starts with **\`main()\`. This function is called by the C++ runtime.**

**Comment by cyphactor** [comment]
@don-reba this should be resolved in master so I am closing this issue now. If you find I missed something and there is still an issue don't hesitate to reopen it.
